version: '2'
services:
    N1DC1:
        labels:
          io.rancher.container.pull_image: always
          io.rancher.scheduler.affinity:host_label: Environment=newhost
          io.rancher.container.network: true
        image: cassandra:3.10
        networks:
            - dc1ring
        volumes:
            - ./n1data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=dev_cluster
            - CASSANDRA_SEEDS=N1DC1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    N2DC1:
        image: cassandra:3.10
        networks:
            - dc1ring
        volumes:
            - ./n2data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=dev_cluster
            - CASSANDRA_SEEDS=N1DC1
        depends_on:
              - N1DC1
        expose:
            # Intra-node communication
            - 7000
            # TLS intra-node communication
            - 7001
            # JMX
            - 7199
            # CQL
            - 9042
            # Thrift service
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    portainer:
        image: portainer/portainer
        networks:
            - dc1ring
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer-data:/data
        ports:
            - "10001:9000"
networks:
    dc1ring:
